/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CreateCommunityRouteImport } from './routes/create-community'
import { Route as FindWorkRouteImport } from './routes/find-work'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as JoinCommunityRouteImport } from './routes/join-community'
import { Route as PostAGigRouteImport } from './routes/post-a-gig'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as VolunteerRouteImport } from './routes/volunteer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateCommunityRoute = CreateCommunityRouteImport.update({
  id: '/create-community',
  path: '/create-community',
  getParentRoute: () => rootRouteImport,
} as any)
const FindWorkRoute = FindWorkRouteImport.update({
  id: '/find-work',
  path: '/find-work',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCommunityRoute = JoinCommunityRouteImport.update({
  id: '/join-community',
  path: '/join-community',
  getParentRoute: () => rootRouteImport,
} as any)
const PostAGigRoute = PostAGigRouteImport.update({
  id: '/post-a-gig',
  path: '/post-a-gig',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create-community': typeof CreateCommunityRoute
  '/find-work': typeof FindWorkRoute
  '/get-started': typeof GetStartedRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/join-community': typeof JoinCommunityRoute
  '/post-a-gig': typeof PostAGigRoute
  '/pricing': typeof PricingRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create-community': typeof CreateCommunityRoute
  '/find-work': typeof FindWorkRoute
  '/get-started': typeof GetStartedRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/join-community': typeof JoinCommunityRoute
  '/post-a-gig': typeof PostAGigRoute
  '/pricing': typeof PricingRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create-community': typeof CreateCommunityRoute
  '/find-work': typeof FindWorkRoute
  '/get-started': typeof GetStartedRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/join-community': typeof JoinCommunityRoute
  '/post-a-gig': typeof PostAGigRoute
  '/pricing': typeof PricingRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/create-community'
    | '/find-work'
    | '/get-started'
    | '/help'
    | '/how-it-works'
    | '/join-community'
    | '/post-a-gig'
    | '/pricing'
    | '/volunteer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/create-community'
    | '/find-work'
    | '/get-started'
    | '/help'
    | '/how-it-works'
    | '/join-community'
    | '/post-a-gig'
    | '/pricing'
    | '/volunteer'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/create-community'
    | '/find-work'
    | '/get-started'
    | '/help'
    | '/how-it-works'
    | '/join-community'
    | '/post-a-gig'
    | '/pricing'
    | '/volunteer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreateCommunityRoute: typeof CreateCommunityRoute
  FindWorkRoute: typeof FindWorkRoute
  GetStartedRoute: typeof GetStartedRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JoinCommunityRoute: typeof JoinCommunityRoute
  PostAGigRoute: typeof PostAGigRoute
  PricingRoute: typeof PricingRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-community': {
      id: '/create-community'
      path: '/create-community'
      fullPath: '/create-community'
      preLoaderRoute: typeof CreateCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-work': {
      id: '/find-work'
      path: '/find-work'
      fullPath: '/find-work'
      preLoaderRoute: typeof FindWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-community': {
      id: '/join-community'
      path: '/join-community'
      fullPath: '/join-community'
      preLoaderRoute: typeof JoinCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-a-gig': {
      id: '/post-a-gig'
      path: '/post-a-gig'
      fullPath: '/post-a-gig'
      preLoaderRoute: typeof PostAGigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreateCommunityRoute: CreateCommunityRoute,
  FindWorkRoute: FindWorkRoute,
  GetStartedRoute: GetStartedRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  JoinCommunityRoute: JoinCommunityRoute,
  PostAGigRoute: PostAGigRoute,
  PricingRoute: PricingRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
